language: python

python:
    - 2.7
    - 3.3
    - 3.4

env:
    global:
        - MINICONDA_VERSION="3.5.5"
        - BOKEH_DEFAULT_TIMEOUT=30
        - secure: "nLrUq2h59KN3k3hnid+Ub4RHDcVkZyrVmuMLoM6NbwKA0bwpDltaoSg5cj2dzdXKBwvv+3VP38oXLhEGLhVi7kDmyX3ICcza6Usy8zgK3s1NBgl6hFjqaJ7RjCu9OP1I42ThMTLfCQMRrYul7s74sGdZa+HfMCZcl+3Co5IzraI="
        - secure: "oI7Up9HuHSBw8k9LBNC6pLEUJONj+5NeEGFpSLSVXvqPPmyXJZ4qRE/dZ/HxZp6xyBze5GLYmdXXAdhrZyNjmU1ZA0rbBLDWLXuAW8eJm5xAXZ0NRFlHMXMkwvbG9hPTOTFtxKNS4lG/Fo5AXwE4MgT5uzQS4I7HuuNkcZOoInY="

matrix:
    include:
        - python: 2.7
          env: BOKEH_DEFAULT_NO_DEV=false BOKEH_DEFAULT_DIFF=FETCH_HEAD
        - python: 2.7
          env: BOKEH_DEFAULT_NO_DEV=true
        - python: 3.3
          env: BOKEH_DEFAULT_NO_DEV=false
        - python: 3.4
          env: BOKEH_DEFAULT_NO_DEV=false
    exclude:
        - python: 2.7
        - python: 3.3
        - python: 3.4

before_install:
    - export PATH="$HOME/miniconda/bin:$PATH"

install:
    - scripts/travis_install

script:
    - nosetests --with-coverage --cover-package=bokeh
    - ( cd sphinx; make all )

notifications:
    flowdock:
        secure: "ZisceYtV2b7LWNUz0wEtiR9TRk+i8x5m/N6+Htn4IFr+bBcBi79ESO0u6DWiJA5rHt+Yq7Yf49vl7UO9HZCF+8n5B1nKpfivJKngVuMYLnhYifNmwCD7vQ8aaF9DTfOqvm2hJrHwtieX8BUGs2KWd8igt3f8LCXVWVBBvkqc2L0="
